version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Cổng RabbitMQ
      - "15672:15672" # Giao diện quản lý
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  product_service:
    build:
      context: ./product_service
    container_name: product_service
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  order_service:
    build:
      context: ./order_service
    container_name: order_service
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - product_service
      - order_service
    environment:
      - PRODUCT_SERVICE_HOST=product_service
      - ORDER_SERVICE_HOST=order_service

networks:
  default:
    name: microservices_network
