global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api_gateway"
    static_configs:
      - targets: ["localhost:5005"]

  - job_name: "order_service"
    static_configs:
      - targets: ["localhost:5003"]

  - job_name: "product_service"
    static_configs:
      - targets: ["localhost:5001"]
